"""Update embedding dimensions from 768 to 3072

Revision ID: 8bdb6bfa8923
Revises: 063f7cdf0cba
Create Date: 2026-02-14 02:02:17.562080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '8bdb6bfa8923'
down_revision: Union[str, Sequence[str], None] = '063f7cdf0cba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Limpar chunks existentes antes de mudar o schema
    op.execute('DELETE FROM document_chunks')

    op.alter_column('document_chunks', 'embedding',
               existing_type=Vector(768),
               type_=Vector(3072),
               existing_nullable=True)
    op.drop_index(op.f('idx_event_rsvps_event'), table_name='event_rsvps', if_exists=True)
    op.drop_index(op.f('idx_event_rsvps_user'), table_name='event_rsvps', if_exists=True)
    op.drop_index(op.f('idx_events_tenant_date'), table_name='events', if_exists=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_events_tenant_date'), 'events', ['tenant_id', 'event_date'], unique=False)
    op.create_index(op.f('idx_event_rsvps_user'), 'event_rsvps', ['user_id'], unique=False)
    op.create_index(op.f('idx_event_rsvps_event'), 'event_rsvps', ['event_id'], unique=False)

    # Limpar chunks antes de mudar o schema de volta
    op.execute('DELETE FROM document_chunks')

    op.alter_column('document_chunks', 'embedding',
               existing_type=Vector(3072),
               type_=Vector(768),
               existing_nullable=True)
    # ### end Alembic commands ###
